FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Minsk

RUN apt-get update && \
    apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

RUN apt-get install -y x11vnc xvfb

RUN useradd -ms /bin/bash u
USER u

RUN pip3 install "kivy[full]" yt-dlp

RUN echo "export PATH=$PATH:~/.local/bin/" >> ~/.bashrc

# Start the VNC server
RUN echo "python3 /app/main.py" > ~/.xinitrc && chmod +x ~/.xinitrc
CMD ["x11vnc", "-create", "-forever"]